Matrix Multiplication: 

First row of 𝐴 with all columns of B:
c11 = (-1)(0) + (2)(0) + (3)(2) = 0 + 0 + 6 = 6
c12 = (-1)(2) + (2)(2) + (3)(9) = -2 + 4 + 27 = 29
c13 = (−1)(1) + (2)(−8) + (3)(-1) = −1 − 16 − 3 = −20

Second row of A with all columns of B:
c21 = (4)(0) + (−5)(0) + (6)(2) = 0 + 0 + 12 = 12
c22 = (4)(2) + (−5)(2) + (6)(9) = 8 − 10 + 54 = 52
c23 = (4)(1) + (−5)(−8) + (6)(−1) = 4 + 40 − 6 = 38

Third row of A with all columns of B:
c31 = (2)(0) + (7)(0) + (8)(2) = 0 + 0 + 16 = 16
c32 = (2)(2) + (7)(2) + (8)(9) = 4 + 14 + 72 = 90
c33 = (2)(1) + (7)(−8) + (8)(−1) = 2 − 56 − 8 = −62

C = AB ={6  29 -20}
        {12 52  38}
        {16 90 -62}

In [1]:
import numpy as np

# Define matrices A and B
A = np.array([
    [-1, 2, 3],
    [4, -5, 6],
    [2, 7, 8]
])

B = np.array([
    [0, 2, 1],
    [0, 2, -8],
    [2, 9, -1]
])

# Compute the matrix product using np.matmul (or equivalently np.dot or @)
C = np.matmul(A, B)

C


array([[  6,  29, -20],
       [ 12,  52,  38],
       [ 16,  90, -62]])

In [2]:
# Define the summation calculation
result = sum(A[0, k] * B[k, 0] for k in range(3))  # Summation for k=0, 1, 2
result


np.int64(6)

In [1]:
import numpy as np

def matrix_multiplication(A, B):
    # Get dimensions
    rows_A, cols_A = len(A), len(A[0])
    rows_B, cols_B = len(B), len(B[0])
    
    # Check if multiplication is possible
    if cols_A != rows_B:
        raise ValueError("Number of columns in A must equal number of rows in B")
    
    # Initialize result matrix with zeros
    C = [[0 for _ in range(cols_B)] for _ in range(rows_A)]
    
    # Compute matrix multiplication
    for i in range(rows_A):
        for j in range(cols_B):
            for k in range(cols_A):
                C[i][j] += A[i][k] * B[k][j]
    
    return C

# Example matrices A and B
A = [[-1, 2, 3],
     [4, -5, 6],
     [7, 8, -9]]

B = [[0, 2, 1],
     [0, 2, -8],
     [2, 9, -1]]

# Perform multiplication
C = matrix_multiplication(A, B)
print("Resultant Matrix C:")
print(np.array(C))


Resultant Matrix C:
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


In [3]:
import numpy as np

def matrix_multiplication(A, B):
    # Validate inputs
    if not isinstance(A, (list, np.ndarray)) or not isinstance(B, (list, np.ndarray)):
        raise TypeError("Both inputs must be 2D lists or NumPy arrays.")

    if not all(isinstance(row, (list, np.ndarray)) for row in A) or not all(isinstance(row, (list, np.ndarray)) for row in B):
        raise TypeError("Both matrices must be 2D lists or NumPy arrays.")

    # Get dimensions
    rows_A, cols_A = len(A), len(A[0])
    rows_B, cols_B = len(B), len(B[0])

    # Ensure all rows have the same length
    if any(len(row) != cols_A for row in A) or any(len(row) != cols_B for row in B):
        raise ValueError("All rows in each matrix must have the same number of columns.")

    # Check for matrix multiplication compatibility
    if cols_A != rows_B:
        raise ValueError(f"Matrix multiplication not possible. Columns of A ({cols_A}) must match rows of B ({rows_B}).")

    # Initialize result matrix with zeros
    C = [[0 for _ in range(cols_B)] for _ in range(rows_A)]

    # Perform matrix multiplication
    for i in range(rows_A):
        for j in range(cols_B):
            for k in range(cols_A):
                C[i][j] += A[i][k] * B[k][j]

    return C

# Example matrices
A = [[-1, 2, 3],
     [4, -5, 6],
     [7, 8, -9]]

B = [[0, 2, 1],
     [0, 2, -8],
     [2, 9, -1]]

# Invalid matrices for testing
D = [[1, 2, 3], 
     [4, 5, 6]]  # Uneven row length

E = [[1, 2], 
     [3, 4]]

# Try with valid matrices
try:
    C = matrix_multiplication(A, B)
    print("Resultant Matrix C:")
    print(np.array(C))
except (ValueError, TypeError) as e:
    print(f"Error: {e}")

# Try with invalid matrices
try:
    C = matrix_multiplication(D, E)
    print("Resultant Matrix C:")
    print(np.array(C))
except (ValueError, TypeError) as e:
    print(f"Error: {e}")


Resultant Matrix C:
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
Error: Matrix multiplication not possible. Columns of A (3) must match rows of B (2).


In [4]:
import numpy as np

def matrix_multiplication_with_transpose(A, B):
    # Transpose the second matrix
    B_transposed = np.transpose(B)  # Alternatively, you can use B.T if B is a NumPy array.

    # Perform matrix multiplication
    result = np.dot(A, B_transposed)  # Dot product handles multiplication.
    return result

# Example matrices
A = np.array([[-1, 2, 3],
              [4, -5, 6],
              [7, 8, -9]])

B = np.array([[0, 2, 1],
              [0, 2, -8],
              [2, 9, -1]])

# Transpose B and compute the product
C = matrix_multiplication_with_transpose(A, B)

print("Matrix A:")
print(A)
print("\nMatrix B (before transpose):")
print(B)
print("\nMatrix B (after transpose):")
print(np.transpose(B))
print("\nResultant Matrix C:")
print(C)


Matrix A:
[[-1  2  3]
 [ 4 -5  6]
 [ 7  8 -9]]

Matrix B (before transpose):
[[ 0  2  1]
 [ 0  2 -8]
 [ 2  9 -1]]

Matrix B (after transpose):
[[ 0  0  2]
 [ 2  2  9]
 [ 1 -8 -1]]

Resultant Matrix C:
[[  7 -20  13]
 [ -4 -58 -43]
 [  7  88  95]]
